### ISSUE TITLE
Mapping Types

### ISSUE THREAD

**Issue by idkjs** [gql-dal/greldal#46]
I have this data-sources/locations.ts file which tries to map this item:

```json
// sample item
{
  "position": {
    "lat": 61.21759217,
    "lng": -149.8935557
  },
  "name": "Starbucks - AK - Anchorage  00001",
  "address": "601 West Street_601 West 5th Avenue_Anchorage, Alaska 99501",
  "phone": "907-277-2477"
}
```

```
import { mapDataSource, mapFields, types } from "greldal";
import { GraphQLID } from "graphql";

// totally made this up, didnt work
// export const Position = mapDataSource({
//   name: 'Position',
//   fields: mapFields({
//     lat: {
//       type: types.number
//     },
//     lng: {
//       type: types.number
//     },
//   })
// });

// this doesnt work either trying [composite types](https://gql-dal.github.io/greldal/mapping-data-sources/)
const position = types.array([
  types.type({
      lat: types.number,
      lng: types.number
  })
]);
export const locations = mapDataSource({
  name: "Location",
  fields: mapFields({
    id: {
      type: types.integer,
      to: GraphQLID,
      isPrimary: true
    },
    name: {
      type: types.string
    },
    address: {
      type: types.string
    },
    phone: {
      type: types.string
    },
    postion: {
      type: position
    }
  })
});
```

This is the complete error: 

```
[nodemon] starting `babel-node --extensions .ts src/index.ts`
/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/graphql/type/schema.js:342
          throw _iteratorError3;
          ^

Error: GraphQL type for Location[fields][postion][] could not be auto-derived. You will need to specify the mapped types yourself.
    at ioToGraphQLInputType (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/greldal/src/graphql-type-mapper.ts:338:11)
    at ioToGraphQLInputType (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/greldal/src/graphql-type-mapper.ts:313:13)
    at Object.exports.deriveFieldInputType (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/greldal/src/graphql-type-mapper.ts:357:5)
    at MappedField.get inputType (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/greldal/src/MappedField.ts:212:16)
    at MappedField.MemoizeGetter.descriptor.get (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/greldal/src/utils.ts:28:27)
    at lodash_1.transform (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/greldal/src/graphql-type-mapper.ts:153:29)
    at /Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/lodash/lodash.js:13807:16
    at /Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/lodash/lodash.js:2996:24)
    at Function.transform (/Users/prisc_000/working/STARBUCKGQL/starbucks-demo/packages/backend/node_modules/lodash/lodash.js:13806:43)
[nodemon] app crashed - waiting for file changes before starting...
```

Thanks for any feedback.

This is the dataset I am using. https://gist.github.com/wf9a5m75/3d40f2d6814ef5f2bc4f75f61d86741e

**Comment by lorefnon** [comment]
@idkjs Thanks for your interest in GRelDAL.

What you are looking for is: 

```
const position = types.array(
  types.type({
      lat: types.number,
      lng: types.number
  })
);
```

Basically the types exposed from GRelDAL are coming from [io-ts](https://github.com/gcanti/io-ts) and you can check their [API docs](https://github.com/gcanti/io-ts#implemented-types--combinators) (for now). In above case `types.array` accepts a single type and not an array.

I agree that this error is not very helpful. Unfortunately, so far I have focussed on those runtime errors which can not be detected by typescript statically. We intend to improve on this significantly in very near future.

Please let me know if the above solves your issue.

**Comment by idkjs** [comment]
Thanks for the response, sir. The syntax compiles but I must have set up the migrations incorrectly. I brought in the `position` key as `json`

```js
export async function up(knex: Knex): Promise<any> {
  return knex.schema.createTable("locations", t => {
    // t.increments will add an id key to each object. Our data doesnt have id keys on it
    t.increments();
    t.string("name").notNullable();
    t.string("address").notNullable();
    t.string("phone");
    t.json("position").notNullable();
  });
};
```

So when I the server I am getting and error on the position. I think I need to use parseFloat from `io-ts`...

```
Server ready at http://localhost:4000/graphql
[GRelDAL:ResolverError:4] TypeError: Location[fields][position] incorrectly specified:
Invalid value {"lat":61.21759217,"lng":-149.8935557} supplied to : Array<{ lat: number, lng: number }>
    at type.decode.getOrElseL.errors (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/greldal/src/assertions.ts:14:15)
    at Left.getOrElseL (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/fp-ts/lib/Either.js:104:16)
    at Object.exports.assertType (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/greldal/src/assertions.ts:13:31)
    at Object.values.map.groupingItem (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/greldal/src/ReverseMapper.ts:93:48)
    at Array.map (<anonymous>)
    at ReverseMapper.reverseMapQueryResults (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/greldal/src/ReverseMapper.ts:86:40)
    at ReverseMapper.reverseMap (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/greldal/src/ReverseMapper.ts:31:32)
    at MappedDataSource.mapRowsToEntities (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/greldal/src/MappedDataSource.ts:329:47)
    at wrapInTransaction (/Users/prisc_000/working/STARBUCKGQL/starbucks-gredal-demo/packages/backend/node_modules/greldal/src/SingleSourceQueryOperationResolver.ts:144:65)
```

Working through it

**Comment by lorefnon** [comment]
Oh, your database doesn't actually contain an array of positions. You can do: 

```
const position = types.json(
  types.type({
      lat: types.number,
      lng: types.number
  })
);
```
